dr: fix 'ansible' ModuleNotFoundError in Disaster Recovery scripts
When executing any Disaster Recovery script, the following error is received:
  [root@storage-ge-13 files]# ./ovirt-dr generate
  Traceback (most recent call last):
    File "./ovirt-dr", line 15, in <module>
      import fail_back
    File "/usr/share/ansible/collections/ansible_collections/redhat/rhv/roles/disaster_recovery/files/fail_back.py", line 14, in <module>
      from ansible.module_utils.six.moves import input
  ModuleNotFoundError: No module named 'ansible'

The reason for that is the following import statement:
  from ansible.module_utils.six.moves import input

There is no need to use "six" library at all since Python2 is deprecated!
All "import"s of "six" module can be deleted now and the builtin Python3
"input()" function will be used instead.

Signed-off-by: Pavel Bar <pbar@redhat.com>
Bug-Url: https://bugzilla.redhat.com/2090264