ovirt_vm: Fix None arguments (#486)
Some arguments can be None in the entity. Which causes the trace below.
Fixing this by using getattr on the possible None values.

Traceback (most recent call last):
  File \"/tmp/ansible_ovirt_vm_payload_8un8pxki/ansible_ovirt_vm_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_vm.py\", line 2671, in main
  File \"/tmp/ansible_ovirt_vm_payload_8un8pxki/ansible_ovirt_vm_payload.zip/ansible_collections/ovirt/ovirt/plugins/module_utils/ovirt.py\", line 644, in create
    if not self.update_check(entity):
  File \"/tmp/ansible_ovirt_vm_payload_8un8pxki/ansible_ovirt_vm_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_vm.py\", line 1689, in update_check
  File \"/tmp/ansible_ovirt_vm_payload_8un8pxki/ansible_ovirt_vm_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_vm.py\", line 1787, in _update_check
AttributeError: 'NoneType' object has no attribute 'enabled'

Co-authored-by: Martin Nečas <necas.marty@gmail.com>